### ISSUE TITLE
README to highlight does not work in threadsafe mode

### ISSUE THREAD

**Issue by seantanly** [evrone/quiet_assets#16]
I believe the readme should include a note on quiet_assets being not threadsafe, and should turn off quiet_assets through config.quiet_assets = false.

It would save users of this gem from some frustration when they are using it in threadsafe mode, and their logs starts to disappear randomly, development mode or not.

Due how quiet_assets work, which is toggling the Rails.logger.level, based on the current implementation of the default Rails logger (3.2.11), it is probably impossible to make it work in threadsafe mode.

Further technical discussion on yell regarding this topic.
https://github.com/rudionrails/yell/issues/4

Thank you for this convenient gem.

**Comment by mchristen** [comment]
Using a Thread local variable won't solve this problem. This is a race condition on the Rails.logger.level object. To solve it a mutex needs to be used around the entire method body, which is probably undesirable for many reasons.

Imagine the following scenario with a rails app running on log level info

    Thread 1: Request arrives
    Thread 1: store Rails.logger.level into method local copy of env hash(saves 'info')
    Thread 2: Request arrives
    Thread 1: set Rails.logger.level = error
    Thread 2: store Rails.logger.level into method local copy of env hash(saves 'error')
    Thread 1: allow app to process request
    Thread 1: set Rails.logger.level = 'info', the value saved earlier in this thread
    Thread 2: allow app to process request
    Thread 2: set Rails.logger.level = 'error', the value saved earlier in this thread

Even if you replaced the location where you are storing the current logging level with a thread safe variable you can not prevent another thread from setting the Rails.logger.level to 'error'.
