### ISSUE TITLE
Assets still shown when logging to stdout

### ISSUE THREAD

**Issue by avk** [evrone/quiet_assets#20]
I set this in development.rb:
`config.logger = ActiveSupport::TaggedLogging.new(Logger.new(STDOUT))`

and was surprised to see asset output with foreman / puma. Should quiet_assets be responsible for that? Or is it just the server logging each request?

**Comment by tomav** [comment]
Same here too, Rails 4 and Puma.
When I start the server using `rails s Puma`, it works (no assets are displayed).

If started using `bundle exec puma -C config/puma.rb`, assets are shown in the log.  

    dev_1 | 192.168.59.3 - - [21/Jul/2015:16:28:37 +0000] "GET /jquery.js?body=1 HTTP/1.1" 304 - 2.3012
    dev_1 | 192.168.59.3 - - [21/Jul/2015:16:28:37 +0000] "GET /jquery-ui/core.js?body=1 HTTP/1.1" 304 - 2.1875
    dev_1 | 192.168.59.3 - - [21/Jul/2015:16:28:38 +0000] "GET /jquery_ujs.js?body=1 HTTP/1.1" 304 - 2.0562

**Comment by route** [comment]
@tomav it's not Rails log you see in the latest output. These requests are all from puma whereas rails and especially QA are beyond the server and don't have ability to affect Puma.

**Comment by tomav** [comment]
@route, yes makes sense. I'll stay on `rails s Puma` on my development env. Thank you.
