### ISSUE TITLE
quiet_assets not quiet assets with thin 2.0.0.pre version in rails 3.2.13

### ISSUE THREAD

**Issue by qichunren** [evrone/quiet_assets#23]
ruby -v
ruby 1.9.3p194

rails 3.2.13
thin 2.0.0.pre
quiet_assets 1.0.2

I start rails with command `bundle exec thin -p 3000`, and all assets request log still output in console.

**Comment by smarquez1** [comment]
No working here either:
``` ruby 2.0.0-p576 ```
