### ISSUE TITLE
Quiet Assets not working on rails 4.2.4

### ISSUE THREAD

**Issue by overdrivemachines** [evrone/quiet_assets#45]
I don't see any difference when I put gem 'quiet_assets', group: :development in my gemfile.
I still see messages like Started GET "/" for 127.0.0.1 at 2015-09-07 20:51:14 -0700

**Comment by route** [comment]
@overdrivemachines You see "/" because it isn't asset path

**Comment by overdrivemachines** [comment]
@route what you are saying does not make sense. In my post I am saying that adding the gem in my gemfile has no effect.

**Comment by route** [comment]
What I'm saying is that in your opened issue you provide a sample of output that has not to be filtered out from the log
