### ISSUE TITLE
Doesn't work with Rails 5 beta and 'no content' responses.

### ISSUE THREAD

**Issue by georgemillo** [evrone/quiet_assets#47]
Don't have time to write a detailed description here, but I just found what I thought was a bug with `rails-5.0.0beta1` and [opened an issue over there](https://github.com/rails/rails/issues/22910). But I've just realised the problem is actually with quiet_assets.

Full explanation in my original rails issue: https://github.com/rails/rails/issues/22910

**Comment by cannikin** [comment]
Just noticed this myself. I'm not seeing any "no content" messages, but my log will only show the first request on a start of `bin/rails server` and nothing nothing else appears in the log after that:

    positron:wnw rob$ bin/rails server
    => Booting Puma
    => Rails 5.0.0.beta1 application starting in development on http://localhost:3000
    => Run `rails server -h` for more startup options
    => Ctrl-C to shutdown server
    I, [2016-01-08T16:14:33.637741 #709]  INFO -- : Celluloid 0.17.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
    Puma 2.15.3 starting...
    * Min threads: 0, max threads: 16
    * Environment: development
    * Listening on tcp://localhost:3001

    Started GET "/" for ::1 at 2016-01-08 16:14:35 -0800
    Processing by PagesController#index as HTML
      Rendered pages/index.html.slim within layouts/application (12.1ms)
    Completed 200 OK in 356ms (Views: 348.3ms | ActiveRecord: 0.0ms)

The pages come up in the browser just fine, it looks like they just don't get logged any more.

But to be fair I don't see all the asset requests, so technically the gem is still working as advertised. ;)

**Comment by jtomaszewski** [comment]
Yup. The same here, even when I used [the current commit](https://github.com/marcroberts/quiet_assets/commit/2ebed8feb045c28b544ef4e45b963bbe52eb4f0b) from https://github.com/evrone/quiet_assets/pull/46 . Seems like there's still some work to be done.

**Comment by marcroberts** [comment]
There is some sort of threading issue going on here. The last failing test with the Rails 5 Gemfile involves the multithreading tests not giving any logging output (it should show some output for some of them), and you're using Puma which is threaded so I suspect you're experiencing the same issue.

I'll keep plugging away to get to the bottom of it

**Comment by ShubhamGupta** [comment]
Not so much sure about threading. I could replicate the issue with Webrick.

**Comment by georgemillo** [comment]
Is this fixed? I just switched from `v1.1.0` to `master` (https://github.com/evrone/quiet_assets/commit/a39a74c4cefd561a1068aecbd4ee67756cd38b98) and the error doesn't seem to be happening anymore (although of course there may be another way of triggering it that I'm missing).

I'm using Ruby 2.2.4 and Rails 5.0.0.beta1.

**Comment by bakku** [comment]
using Rails 5.0.0.beta2 and Ruby 2.3.0. Can confirm that I have the same issue. ``quiet_assets`` is not really usable like this for me

**Comment by u007** [comment]
its running on my side , but i get this warning.
using 5.0.0.beta2

ARN -- : DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from block (2 levels) in <class:Engine> at /usr/local/rvm/gems/ruby-2.2.2/bundler/gems/quiet_assets-a39a74c4cefd/lib/quiet_assets.rb:32)

**Comment by joshuaflanagan** [comment]
I think the best approach might be to abandon trying to manage the logger level within quiet_assets, and rely on `Rails.logger.silence` to do it. The rails team is going through the trouble of trying to make it work in a proper multithreaded way (though it isn't quite working yet https://github.com/rails/rails/issues/23609) - no need to repeat that effort here.

quiet_assets becomes something like:

```
      module RackWithQuietAssets
        def call(env)
          if env['PATH_INFO'] =~ ASSETS_REGEX
            Rails.logger.silence do
              super(env)
            end
          else
            super(env)
          end
        end
      end
```

**Comment by dhh** [comment]
I'd like to see this feature moved into Rails as an option. Definitely a fan of this!

**Comment by saratovsource** [comment]
:+1:

**Comment by stereodenis** [comment]
:+1:

**Comment by joshuaflanagan** [comment]
Exact same conclusion I came to when I realized it should just use `Rails.logger.silence`. No reason for the gem to exist independently if Rails is doing all the hard work.

**Comment by saigemcvea** [comment]
:+1:

**Comment by lfalcao** [comment]
:+1:

**Comment by KODerFunk** [comment]
:+1:

**Comment by luckylu** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by luckylu** [comment]
:+1:

**Comment by kle-roy** [comment]
:+1:

**Comment by iloveitaly** [comment]
I expanded on @joshuaflanagan's work a bit. Here's a drop-in replacement for `quiet_assets`:

```ruby
class RackWithQuietAssets
  def initialize(app)
    @app = app

    quiet_assets_paths = [ %r[\A/{0,2}#{Rails.application.config.assets.prefix}] ]
    @assets_regex = /\A(#{quiet_assets_paths.join('|')})/
  end

  def call(env)
    if env['PATH_INFO'] =~ @assets_regex
      Rails.logger.silence do
        @app.call(env)
      end
    else
      @app.call(env)
    end
  end
end

# application.rb

config.middleware.insert_after ActionDispatch::Static, RackWithQuietAssets
```

**Comment by cannikin** [comment]
@iloveitaly's solution works great! Created `app/middleware/rack_with_quiet_assets.rb` and added the config in `config/environments/development.rb` — voila!

**Comment by connorshea** [comment]
@dhh was this ever added to Rails 5? :)

**Comment by dhh** [comment]
Wasn't. Feel free to take a stab at it!

**Comment by connorshea** [comment]
@dhh is there any relevant issue open in the Rails project?

**Comment by dhh** [comment]
Not that I know of. Feel free to open a PR.

**Comment by wenweih** [comment]
[Development logging is inconsistent in Rails 5 beta 3](https://github.com/rails/rails/issues/24251)

**Comment by wenweih** [comment]
#42

**Comment by dbackeus** [comment]
So Rails 5 is out and quiet assets still incompatible. Any progress or alternatives?

**Comment by cannikin** [comment]
@dbackeus See @iloveitaly's middleware above.

**Comment by connorshea** [comment]
@dbackeus This is built into sprockets-rails now: https://github.com/rails/sprockets-rails/pull/355

Note that it'll only work with Rails 4.2.7/5.0.0

**Comment by connorshea** [comment]
See also: https://github.com/evrone/quiet_assets#deprecation
