### ISSUE TITLE
Why use ENV[key] rather than a class variable?

### ISSUE THREAD

**Issue by justin808** [evrone/quiet_assets#48]
https://github.com/evrone/quiet_assets/blob/master/lib%2Fquiet_assets.rb#L23

Could you use a class variable rather than using the ENV Hash?

**Comment by dgynn** [comment]
@justin808 In this context, the `env` is a Rack "environment" and not a Ruby `ENV` to access environment variables. 
The Rack `env` is a Hash.
http://www.rubydoc.info/github/rack/rack/master/file/SPEC
